### ISSUE TITLE
do not forward to login-page on hangup

### ISSUE THREAD

**Issue by r10s** [cracker0dks/basicwebrtc#10]
clicking "hangup" on ending a call on mobile now redirects to an unrelated nextcloud page; this is pretty confusing.

we should redirect to a more of less empty, maybe static html-page that just says "you can close this window now".

successor of https://github.com/cracker0dks/basicwebrtc/issues/6

**Comment by cracker0dks** [comment]
correct, this was a subdir url problem. Fixed: 9385e26bb39e7286fc7c612500c5dd92be445e0b
