### ISSUE TITLE
enable cam on start

### ISSUE THREAD

**Issue by r10s** [cracker0dks/basicwebrtc#11]
with #5, request video- and audio-rights are _requested_ in on step, however, video should also be _enabled_ by default.

maybe we can have a parameter as cam=off to force audio-only calls.

**Comment by cracker0dks** [comment]
done: https://github.com/cracker0dks/basicwebrtc/commit/7a339f7f164b9b1ecbca740121874bf71d57ca50

**Comment by r10s** [comment]
great! thanks a lot!
