### ISSUE TITLE
Indication who is currently speaking

### ISSUE THREAD

**Issue by Simon-Laux** [cracker0dks/basicwebrtc#17]
like a border around the avatar circle that appears when the person speaks, like in discord or Skype.
This would solve one of the problems, which make @r10s wanting always on video by default:
If your system sound is muted you don't hear people, but also currently have no indication that there is being sound transferred, so you could think the problem is on their side in their microphone for example.
With the indication you could see that the microphone is indeed working and sound is being transferred.

**Comment by cracker0dks** [comment]
add this feature to the current master 👍
