### ISSUE TITLE
Idea: Picture in Picture mode

### ISSUE THREAD

**Issue by Simon-Laux** [cracker0dks/basicwebrtc#20]
not sure how possible this is, but that way you could see your video chat partner even while working with other apps, could also work nicely together with screen share - you could still see the other person while you share your screen

**Comment by cracker0dks** [comment]
I added this feature for all supported browsers: https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API#browser_compatibility 
In all browsers you should also be able to just right click on the video and select: Picture in Picture. Even if they don't have the javascript api support.
